# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20181214_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(default='myphoto'),
        ),
    ]
